@startuml WineInventoryDomain
skinparam monochrome true

package "WineInventory.Shared.Domain" {
  package "Model" {
    package "Aggregates" {
      class "AuditableAbstractAggregateRoot" as Shared_AuditableAbstractAggregateRoot <<abstract>> {
        #createdAt: Date
        #updatedAt: Date
        --
        +addDomainEvent(event: Object): void
      }
    }

    package "Entities" {
      class "AuditableModel" as Shared_AuditableModel {
        +id: Long
        +createdAt: Date
        +updatedAt: Date
      }
    }

    package "ValueObjects" {
      class "Money" as Shared_Money <<record>> {
        +amount: Double
        +currency: String
        --
        +toString(): String
      }
    }
  }
}

package "WineInventory.Authorization.Domain" {
  package "Model" {
    package "Aggregates" {
      class "User" as Auth_User { }
    }
    package "Events" {
      class "AccountOwnerUserCreatedEvent" as AccountOwnerUserCreatedEvent { }
    }
    package "Queries" {
      class "GetUserByIdQuery" as GetUserByIdQuery { }
      class "GetUserByEmailQuery" as GetUserByEmailQuery { }
      class "GetAllUsersByAccountIdQuery" as GetAllUsersByAccountIdQuery { }
    }
    package "ValueObjects" {
      enum "UserRoles" as UserRoles {
      }
    }
    package "Commands" {
      class "SignInCommand" as SignInCommand { }
      class "SignUpCommand" as SignUpCommand { }
      class "CreateUserCommand" as CreateUserCommand { }
      class "GoogleSignInCommand" as GoogleSignInCommand { }
    }
  }


  package "Services" {
    interface "UserCommandService" as UserCommandService { }
    interface "UserQueryService" as UserQueryService { }
    interface "GoogleAuthService" as GoogleAuthService { }
  }


  package "Repositories" {
    interface "UserRepository" as UserRepository { }
  }


  UserRepository ..> Auth_User : uses
  Auth_User "1" --> "1" UserRoles : role
  UserCommandService ..> CreateUserCommand : uses
  UserQueryService ..> GetUserByIdQuery : uses
  UserQueryService ..> GetUserByEmailQuery : uses
  UserQueryService ..> GetAllUsersByAccountIdQuery : uses
  GoogleAuthService ..> GoogleSignInCommand : uses
}


package "WineInventory.AlertsAndNotifications.Domain" {
  package "Model" {
    package "Aggregates" {
      class "Alert" as Alert {
        +alertId: Long
        +title: String
        +message: String
        +severity: SeverityTypes
        +type: AlertTypes
        +resolvedAt: Date
      }
    }

    package "ValueObjects" {
      class "AccountId" as Alerts_AccountId { }
      class "ProductId" as Alerts_ProductId { }
      class "WarehouseId" as Alerts_WarehouseId { }
      enum "AlertState" as AlertState {
        ACTIVE
        NOT_READ
        READ
        RESOLVED
      }
      enum "SeverityTypes" as Alerts_SeverityTypes {
        LOW
        MEDIUM
        HIGH
        WARNING
      }
      enum "AlertTypes" as Alerts_AlertTypes {
        PRODUCTLOWSTOCK
        EXPIRATION_WARNING
        SYSTEM_ALERT
        MAINTENANCE
      }
    }

    package "Commands" {
      class "CreateAlertCommand" as CreateAlertCommand { }
      class "MarkAlertAsReadCommand" as MarkAlertAsReadCommand { }
    }

    package "Queries" {
      class "GetAlertByIdQuery" as GetAlertByIdQuery { }
    }
  }


  package "Repositories" {
    interface "AlertRepository" as AlertRepository { }
  }


  package "Services" {
    interface "AlertCommandService" as AlertCommandService { }
    interface "AlertQueryService" as AlertQueryService { }
  }


  Alert --> Alerts_ProductId : productId
  Alert --> Alerts_WarehouseId : warehouseId
  Alert --> AlertState : state
  AlertRepository ..> Alert : manages
  AlertCommandService ..> CreateAlertCommand : uses
  AlertCommandService ..> MarkAlertAsReadCommand : uses
  AlertQueryService ..> GetAlertByIdQuery : uses
}


package "WineInventory.InventoryManagement.Domain" {
  package "Model" {
    package "Aggregates" {
      class "Product" as IM_Product {
        +productId: Long
        +liquorType: String
        +brandName: String
        +productName: String
        +unitPrice: Money
        +minimumStock: Integer
        +imageUrl: String
      }
      class "Inventory" as IM_Inventory {
        +inventoryId: Long
        +productStock: Integer
        +productState: ProductState
        +productBestBeforeDate: LocalDate
      }
      class "Warehouse" as IM_Warehouse {
        +warehouseId: Long
        +name: String
      }
    }

    package "Entities" {
      class "ProductExit" as IM_ProductExit { }
    }

    package "Events" {
      class "ProductProblemDetectedEvent" as ProductProblemDetectedEvent { }
    }

    package "Commands" {
      class "CreateProductCommand" as CreateProductCommand { }
      class "UpdateProductCommand" as UpdateProductCommand { }
      class "DeleteProductCommand" as DeleteProductCommand { }
      class "CreateWarehouseCommand" as CreateWarehouseCommand { }
      class "UpdateWarehouseCommand" as UpdateWarehouseCommand { }
    }

    package "Queries" {
      class "GetAllProductsByAccountIdQuery" as GetAllProductsByAccountIdQuery { }
      class "GetProductByIdQuery" as GetProductByIdQuery { }
      class "GetAllWarehousesByAccountIdQuery" as GetAllWarehousesByAccountIdQuery { }
    }

    package "ValueObjects" {
      class "AccountId" as IM_AccountId { }
      enum "LiquorType" as IM_LiquorType {
        WINE
        WHISKY
        RUM
        TEQUILA
        SODA
        SNACK
      }
      enum "ProductState" as IM_ProductState {
        With_Stock
        Out_Of_Stock
      }
      class "ImageUrl" as IM_ImageUrl { }
      class "ProductName" as IM_ProductName { }
      class "WarehousesAddress" as IM_WarehousesAddress { }
    }
  }


  package "Repositories" {
    interface "ProductRepository" as ProductRepository { }
    interface "InventoryRepository" as InventoryRepository { }
    interface "WarehouseRepository" as WarehouseRepository { }
  }


  package "Services" {
    interface "ProductCommandService" as ProductCommandService { }
    interface "ProductQueryService" as ProductQueryService { }
    interface "InventoryCommandService" as InventoryCommandService { }
    interface "InventoryQueryService" as InventoryQueryService { }
    interface "WarehouseCommandService" as WarehouseCommandService { }
    interface "WarehouseQueryService" as WarehouseQueryService { }
  }


  IM_Product "1" --> "*" IM_Inventory : inventories
  IM_Inventory "*" --> "1" IM_Product : product
  IM_Inventory "*" --> "1" IM_Warehouse : warehouse
  IM_Product --> Shared_Money : unitPrice
  IM_Product --> IM_ProductName : productName
  IM_Product --> IM_ImageUrl : imageUrl
  IM_Product --> IM_LiquorType : liquorType
  IM_Product --> IM_AccountId : accountId
  IM_Inventory --> IM_ProductState : productState
  IM_Warehouse --> IM_WarehousesAddress : address
  ProductRepository ..> IM_Product : manages
  InventoryRepository ..> IM_Inventory : manages
  WarehouseRepository ..> IM_Warehouse : manages
  ProductCommandService ..> CreateProductCommand : uses
  ProductCommandService ..> UpdateProductCommand : uses
  ProductCommandService ..> DeleteProductCommand : uses
  ProductQueryService ..> GetProductByIdQuery : uses
  ProductQueryService ..> GetAllProductsByAccountIdQuery : uses
  WarehouseCommandService ..> CreateWarehouseCommand : uses
  WarehouseCommandService ..> UpdateWarehouseCommand : uses
  WarehouseQueryService ..> GetAllWarehousesByAccountIdQuery : uses
}

package "WineInventory.OrderOperationAndMonitoring.Domain" {
  package "Model" {
    package "Aggregates" {
      class "SalesOrder" as OOM_SalesOrder { }
    }
    package "Entities" {
      class "SalesOrderItem" as OOM_SalesOrderItem { }
    }
    package "Commands" {
      class "GenerateSalesOrderCommand" as GenerateSalesOrderCommand { }
    }
    package "Events" {
      class "OrderCompletedEvent" as OrderCompletedEvent { }
    }
    package "Queries" {
      class "GetAllSalesOrdersByBuyerIdQuery" as GetAllSalesOrdersByBuyerIdQuery { }
    }
    package "ValueObjects" {
      interface "Deliverable" as Deliverable { }
    }
  }


  package "Services" {
    interface "SalesOrderCommandService" as SalesOrderCommandService { }
  }


  package "Repositories" {
    interface "SalesOrderRepository" as SalesOrderRepository { }
  }


  OOM_SalesOrder "1" o-- "*" OOM_SalesOrderItem : contains
  OOM_SalesOrderItem "1" --> "1" IM_Product : product
  OOM_SalesOrder ..> Deliverable : implements
  SalesOrderRepository ..> OOM_SalesOrder : uses
  SalesOrderCommandService ..> GenerateSalesOrderCommand : uses
}

package "WineInventory.ProfileManagement.Domain" {
  package "Model" {
    package "Aggregates" {
      class "Profile" as Profile {
        +profileId: Long
        +fullName: String
        +role: String
        +email: String
        +phone: String
        +location: String
        +username: String
        +avatarUrl: String
      }
    }

    package "ValueObjects" {
      class "PersonName" as PersonName { }
    }

    package "Commands" {
      class "CreateProfileCommand" as CreateProfileCommand { }
      class "UpdateProfileCommand" as UpdateProfileCommand { }
    }

    package "Queries" {
      class "GetAllProfilesQuery" as GetAllProfilesQuery { }
    }
  }


  package "Services" {
    interface "ProfileCommandService" as ProfileCommandService { }
    interface "ProfileQueryService" as ProfileQueryService { }
  }


  package "Repositories" {
    interface "ProfileRepository" as ProfileRepository { }
  }


  Profile --> PersonName : name
  ProfileRepository ..> Profile : manages
  ProfileCommandService ..> CreateProfileCommand : uses
  ProfileCommandService ..> UpdateProfileCommand : uses
  ProfileQueryService ..> GetAllProfilesQuery : uses
}

package "WineInventory.ReportingAndCareGuide.Domain" {
  package "Model" {
    package "Aggregates" {
      class "CareGuide" as CareGuide {
        +careGuideId: Long
        +name: String
        +type: String
        +description: String
        +imageUrl: String
      }
      class "Report" as Report {
        +reportId: Long
        +products: String
        +type: String
        +price: Double
        +amount: Double
        +date: Date
        +lost: Double
      }
    }

    package "Commands" {
      class "CreateReportCommand" as CreateReportCommand { }
      class "DeleteReportCommand" as DeleteReportCommand { }
    }

    package "Queries" {
      class "GetReportByIdQuery" as GetReportByIdQuery { }
      class "GetReportByProductNameQuery" as GetReportByProductNameQuery { }
      class "GetReportByReportDateAndLostAmountQuery" as GetReportByReportDateAndLostAmountQuery { }
      class "GetReportByTypeQuery" as GetReportByTypeQuery { }
    }

    package "ValueObjects" {
      class "ProductId" as RC_ProductId { }
    }

    package "Exceptions" {
      class "DuplicateReportException" as DuplicateReportException { }
    }
  }


  package "Repositories" {
    interface "ReportRepository" as ReportRepository { }
    interface "CareGuideRepository" as CareGuideRepository { }
  }


  package "Services" {
    interface "ReportCommandService" as ReportCommandService { }
    interface "ReportQueryService" as ReportQueryService { }
    class "ImageService" as ImageService { }
  }


  ReportCommandService ..> CreateReportCommand : uses
  ReportCommandService ..> DeleteReportCommand : uses
  ReportQueryService ..> GetReportByIdQuery : uses
  ReportQueryService ..> GetReportByProductNameQuery : uses
  ReportQueryService ..> GetReportByReportDateAndLostAmountQuery : uses
  ReportQueryService ..> GetReportByTypeQuery : uses
  ReportRepository ..> Report : manages
  CareGuideRepository ..> CareGuide : manages
  Report --> RC_ProductId : product
  ImageService ..> CareGuide : process images
}


@enduml
